#!/usr/bin/env bash
set -euo pipefail

# Syncs shippable skills from thananon/9arm-skills into .claude/skills/.
#
# "Shippable" follows the upstream convention: every skill directory with a
# SKILL.md, excluding the personal/, in-progress/, and deprecated/ buckets.
# Local-only skills (anything listed in KEEP below) are never touched.
#
# Usage: ./scripts/sync-skills.sh [ref]
#   ref — upstream branch/tag/commit to sync from (default: main)

UPSTREAM_REPO="https://github.com/thananon/9arm-skills.git"
REF="${1:-main}"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/.claude/skills"
MANIFEST="$DEST/UPSTREAM.lock"

# Skills that live in this repo only — never removed by a sync.
KEEP=("brand-guidelines" "remotion-best-practices")

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "Fetching $UPSTREAM_REPO @ $REF ..."
git clone --quiet --depth 1 --branch "$REF" "$UPSTREAM_REPO" "$TMP/upstream"
COMMIT="$(git -C "$TMP/upstream" rev-parse HEAD)"

mkdir -p "$DEST"

# Remove previously synced upstream skills (everything not in KEEP) so that
# skills deleted upstream don't linger here.
for dir in "$DEST"/*/; do
  [ -d "$dir" ] || continue
  name="$(basename "$dir")"
  keep=false
  for k in "${KEEP[@]}"; do
    [ "$name" = "$k" ] && keep=true && break
  done
  $keep || rm -rf "$dir"
done

synced=()
while IFS= read -r -d '' skill_md; do
  src="$(dirname "$skill_md")"
  name="$(basename "$src")"
  cp -r "$src" "$DEST/$name"
  synced+=("$name")
  echo "synced $name"
done < <(find "$TMP/upstream/skills" -name SKILL.md \
  -not -path '*/node_modules/*' \
  -not -path '*/deprecated/*' \
  -not -path '*/in-progress/*' \
  -not -path '*/personal/*' \
  -print0 | sort -z)

{
  echo "# Generated by scripts/sync-skills.sh — do not edit by hand."
  echo "repo: $UPSTREAM_REPO"
  echo "ref: $REF"
  echo "commit: $COMMIT"
  echo "synced_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "skills:"
  for s in "${synced[@]}"; do echo "  - $s"; done
} > "$MANIFEST"

echo
echo "Done. ${#synced[@]} skill(s) synced from $COMMIT."
echo "Manifest written to ${MANIFEST#"$ROOT"/}."
